#+title: Wordle Tools
#+description: Practicing with racket-lang with wordle as a canvas
#+author: jcottrell

#+export_file_name: ../readme.md
# C-c C-e m m to export to markdown

* Wordle Tools
Playing with wordle as practice for real life.
** Short list of tools
+ Answer finder for _today_ or any arbitrary date: pull the list of answers and get the requested answer (nothing passed in means _today_, arbitrary dates should have the form yyyy-mm-dd)
+ Answer searcher to lookup words that have or will appear as wordle answers. It gives the date and wordle day of when the answer has or will appear.
** Running the tools
+ With Racket installed...
+ Run with
  =racket get-wordle-answer.rkt=
  or
  =racket get-wordle-answer.rkt "2022-08-01"=
+ Or compile with =raco exe search-answers.rkt= then run with =./search-answers cigar=
** Potential future tools
+ GUI tools (for answer finders).
+ Browser bookmarklet connection to server to help players stay away from mistakenly re-using letters or spaces when they don't want to.
+ Auto-guesser that will allow developers to add their own set of specially named functions to guess answers, essentially allowing them to test their own play strategies.
+ Create your own wordle-esque site with just enough differences for legal separation.
** TODONEs
+ Added storage interface (rudimentary) and implemented it in with file storage first.
** TODO
+ Keep everything in racket to practice app, website, api, etc. design and patterns.
+ Implement storage interface with database storage.
+ Create a UI/UX interface via an app and also a website.
+ Make each tool distributable.
+ Add API for allow others to pull words.
+ Add text-message capability.
